port_base: 10001
site_name: Docudrome
site_tagline: Knowledge & Fun
item_name: Doc
item_description: A piece of data that seems interesting to read
tuit_sentence: the {{at}} somebody storaged <strong><a href="/tuits/{{tuit}}">{{tuit}}</a></strong> in our server (<a href="/tuits.json">here!</a>).
tuit_consideration: For sure <strong><a href="/tuits/{{tuit}}">{{tuit}}</a></strong> is important to reach THE FIX we need.
