lovedrome: author,autor,speaker,featuring,vía,ponente,madre,padre,hermano,hermana,amiga,amigo,pedalea
docudrome: talk,doc,spec,codetail,charla,parte de,parte
notedrome: note,reflexion,thought,monolog,dialog,triatlog,conversation
eventodrome: event,evento,meet
petodrome: animal,pet
vegidrome: plant,tree,flower,cactus
projectdrome: project,proyecto,site,sitio,comisión,depende de
