lovedrome: author,autor,speaker,featuring,vía,ponente,madre,padre,hermano,hermana,amiga,amigo
docudrome: talk,doc,spec,codetail
notedrome: note,reflexion,thought,monolog,dialog,triatlog,conversation
eventodrome: event,evento,meet
petodrome: animal,pet
vegidrome: plant,tree,flower,cactus
projectdrome: project,proyecto,site,sitio
