lovedrome: author,autora,autor,speaker,featuring,vía,ponente,madre,padre,hermano,hermana,amiga,amigo,pedalea,compañera,compañero
docudrome: talk,doc,spec,codetail,charla,parte de,parte,obra,trabajo,recommend
notedrome: note,reflexion,thought,monolog,dialog,triatlog,conversation
eventodrome: event,evento,meet,quedada,open,hackathon,hackatón,organiza
petodrome: animal,pet
vegidrome: plant,tree,flower,cactus
projectdrome: project,proyecto,site,sitio,comisión,depende de,organizador
