created_at: Moment when the *auido* was first submitted.
auido: The word we use to remember about this entry. In this drome ({{site_name}}) is a {{item_description}}
identity: Ownership/s of the entry.
madrino: Indentity/ies of people that think this entry is interesting.
